<?php


namespace App\classes;
use App\classes\User;
use App\classes\ExampleOne;
use App\classes\ExampleTwo;
use App\classes\ExampleThree;
use App\classes\ExampleFour;
class Teacher extends ExampleThree implements ExampleOne ,ExampleTwo
{
    use ExampleFour;
    public $mobile;
    public $test;

    public function __construct()
    {
        $this->mobile ='012585366';
        $this->name ='Basis';
        $this->email='basis@gmail.com';
    }

    public function  view()
    {
        $this->hello();
//        echo  "User name is $this->name and email address is $this->email and mobile is $this->mobile";
    }
    public function one()
{
    $this->hello();
    echo 'Hello one';
}
    public function two()
    {
        echo 'Hello two';
    }
    public function three()
    {
        echo 'Hello three';
    }
    public function four()
    {
        echo 'Hello four';
    }
    public function five()
    {
        echo 'Hello five';
    }
   public function twenty(){
        echo 'Hello';
    }
    public function ten()
    {
        $this->test=parent::ten(); // TODO: Change the autogenerated stub
        echo  $this->test.'this is custom';
    }
}